/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FeColorMatrixDemo: typeof import('./src/components/feColorMatrixDemo.vue')['default']
    SvgFilter: typeof import('./src/components/SvgFilter.vue')['default']
  }
}
